export const NewestGames = [
    {
      image: "/card1.png",
      alt: "card1",
      title: "Core Philosophies",
      profilePic: "user1.png",
      username: "Cameron Williamson",
      character: "Gillette",
    },
    {
      image: "/card2.png",
      alt: "card2",
      title: "Leadership Values",
      profilePic: "user2.png",
      username: "John Doe",
      character: "Manager",
    },
    {
      image: "/card3.png",
      alt: "card3",
      title: "Business Strategies",
      profilePic: "user3.png",
      username: "Jane Smith",
      character: "Entrepreneur",
    },
    {
      image: "/card4.png",
      alt: "card4",
      title: "Market Trends",
      profilePic: "user4.png",
      username: "Michael Brown",
      character: "Analyst",
    },
    {
      image: "/card5.png",
      alt: "card5",
      title: "Financial Planning",
      profilePic: "user5.png",
      username: "Sarah Wilson",
      character: "Investor",
    },
    {
      image: "/card6.png",
      alt: "card6",
      title: "Innovative Thinking",
      profilePic: "user6.png",
      username: "David Johnson",
      character: "Creative Director",
    },
  ];

  export const LatestGames = [
    {
        image: "/card6.png",
        alt: "card6",
        title: "Innovative Thinking",
        profilePic: "user6.png",
        username: "David Johnson",
        character: "Creative Director",
      },
      {
        image: "/card5.png",
        alt: "card5",
        title: "Financial Planning",
        profilePic: "user5.png",
        username: "Sarah Wilson",
        character: "Investor",
      },
      {
        image: "/card4.png",
        alt: "card4",
        title: "Market Trends",
        profilePic: "user4.png",
        username: "Michael Brown",
        character: "Analyst",
      },
      {
        image: "/card3.png",
        alt: "card3",
        title: "Business Strategies",
        profilePic: "user3.png",
        username: "Jane Smith",
        character: "Entrepreneur",
      },
      {
        image: "/card2.png",
        alt: "card2",
        title: "Leadership Values",
        profilePic: "user2.png",
        username: "John Doe",
        character: "Manager",
      },
      {
        image: "/card1.png",
        alt: "card1",
        title: "Core Philosophies",
        profilePic: "user1.png",
        username: "Cameron Williamson",
        character: "Gillette",
      },
  ]

  export const fightGames = [{
    
        image: "/card4.png",
        alt: "card4",
        title: "Market Trends",
        profilePic: "user4.png",
        username: "Michael Brown",
        character: "Analyst",
      },
      {
        image: "/card5.png",
        alt: "card5",
        title: "Financial Planning",
        profilePic: "user5.png",
        username: "Sarah Wilson",
        character: "Investor",
      },
      {
        image: "/card6.png",
        alt: "card6",
        title: "Innovative Thinking",
        profilePic: "user6.png",
        username: "David Johnson",
        character: "Creative Director",
      },
      {
        image: "/card1.png",
        alt: "card1",
        title: "Core Philosophies",
        profilePic: "user1.png",
        username: "Cameron Williamson",
        character: "Gillette",
      },
      {
        image: "/card2.png",
        alt: "card2",
        title: "Leadership Values",
        profilePic: "user2.png",
        username: "John Doe",
        character: "Manager",
      },
      {
        image: "/card3.png",
        alt: "card3",
        title: "Business Strategies",
        profilePic: "user3.png",
        username: "Jane Smith",
        character: "Entrepreneur",
      },
  ]

  export const sportGames = [
    {
      image: "/card1.png",
      alt: "card1",
      title: "Core Philosophies",
      profilePic: "user1.png",
      username: "Cameron Williamson",
      character: "Gillette",
    },
    {
      image: "/card2.png",
      alt: "card2",
      title: "Leadership Values",
      profilePic: "user2.png",
      username: "John Doe",
      character: "Manager",
    },
    {
      image: "/card3.png",
      alt: "card3",
      title: "Business Strategies",
      profilePic: "user3.png",
      username: "Jane Smith",
      character: "Entrepreneur",
    },
    {
      image: "/card4.png",
      alt: "card4",
      title: "Market Trends",
      profilePic: "user4.png",
      username: "Michael Brown",
      character: "Analyst",
    },
    {
      image: "/card5.png",
      alt: "card5",
      title: "Financial Planning",
      profilePic: "user5.png",
      username: "Sarah Wilson",
      character: "Investor",
    },
    {
      image: "/card6.png",
      alt: "card6",
      title: "Innovative Thinking",
      profilePic: "user6.png",
      username: "David Johnson",
      character: "Creative Director",
    },
  ];